<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Prasannakumar" failures="1" tests="13" name="alert" time="25.491" errors="0" timestamp="2024-04-24T09:55:13 IST">
  <testcase classname="alerts.demoAnnotation" name="m1" time="0.009"/>
  <testcase classname="alerts.demoAnnotation" name="m2" time="0.001"/>
  <testcase classname="alerts.demoAnnotation" name="m2" time="0.001"/>
  <testcase classname="alerts.demoAnnotation" name="m2" time="0.001"/>
  <testcase classname="alerts.demoAnnotation" name="m3" time="1.019">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method alerts.demoAnnotation.m3() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method alerts.demoAnnotation.m3() didn't finish within the time-out 1000
at java.base@17.0.8/java.lang.Thread.sleep(Native Method)
at app//alerts.demoAnnotation.m3(demoAnnotation.java:25)
at java.base@17.0.8/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@17.0.8/java.lang.Thread.run(Thread.java:833)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- m3 -->
  <testcase classname="alerts.AboutAlerts" name="confirmationAlert" time="4.084"/>
  <testcase classname="alerts.AboutAlerts" name="normalAlert" time="4.098"/>
  <testcase classname="alerts.AboutAlerts" name="promptAlert" time="2.08"/>
  <testcase classname="alerts.attribuets" name="login" time="0.003"/>
  <testcase classname="alerts.attribuets" name="Clickoncatalog" time="0.002"/>
  <testcase classname="alerts.dump" name="m4" time="0.002"/>
  <testcase classname="alerts.dump" name="m5" time="0.001"/>
  <testcase classname="alerts.dump" name="m6" time="0.002"/>
</testsuite> <!-- alert -->
